WITH stg_customers AS (
  SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME
  FROM {{ ref('stg_customers') }}
), orders AS (
  SELECT
    ORDER_ID,
    LOCATION_ID,
    CUSTOMER_ID,
    SUBTOTAL_CENTS,
    TAX_PAID_CENTS,
    ORDER_TOTAL_CENTS,
    SUBTOTAL,
    TAX_PAID,
    ORDER_TOTAL,
    ORDERED_AT,
    ORDER_COST,
    ORDER_ITEMS_SUBTOTAL,
    COUNT_FOOD_ITEMS,
    COUNT_DRINK_ITEMS,
    COUNT_ORDER_ITEMS,
    IS_FOOD_ORDER,
    IS_DRINK_ORDER,
    CUSTOMER_ORDER_NUMBER
  FROM {{ ref('orders') }}
), formula_1 AS (
  SELECT
    *,
    COUNT(DISTINCT ORDER_ID) > 1 AS IS_REPEAT_BUYER
  FROM orders
), aggregate_1 AS (
  SELECT
    CUSTOMER_ID,
    COUNT(DISTINCT ORDER_ID) AS COUNT_LIFETIME_ORDERS,
    MIN(ORDERED_AT) AS FIRST_ORDERED_AT,
    MAX(ORDERED_AT) AS LAST_ORDERED_AT,
    SUM(SUBTOTAL) AS LIFETIME_SPEND_PRETAX,
    SUM(TAX_PAID) AS LIFETIME_TAX_PAID,
    SUM(ORDER_TOTAL) AS LIFETIME_SPEND
  FROM formula_1
  GROUP BY
    CUSTOMER_ID
), join_1 AS (
  SELECT
    stg_customers.CUSTOMER_ID,
    stg_customers.CUSTOMER_NAME,
    aggregate_1.COUNT_LIFETIME_ORDERS,
    aggregate_1.FIRST_ORDERED_AT,
    aggregate_1.LAST_ORDERED_AT,
    aggregate_1.LIFETIME_SPEND_PRETAX,
    aggregate_1.LIFETIME_TAX_PAID,
    aggregate_1.LIFETIME_SPEND,
    aggregate_1.IS_REPEAT_BUYER
  FROM stg_customers
  LEFT JOIN aggregate_1
    ON stg_customers.CUSTOMER_ID = aggregate_1.CUSTOMER_ID
), formula_2 AS (
  SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    COUNT_LIFETIME_ORDERS,
    FIRST_ORDERED_AT,
    LAST_ORDERED_AT,
    LIFETIME_SPEND_PRETAX,
    LIFETIME_TAX_PAID,
    LIFETIME_SPEND,
    CASE WHEN IS_REPEAT_BUYER THEN 'returning' ELSE 'new' END AS CUSTOMER_TYPE
  FROM join_1
), customers AS (
  SELECT
    *
  FROM formula_2
)
SELECT
  *
FROM customers