WITH stg_customers AS (
  SELECT
    *
  FROM {{ ref('stg_customers') }}
), orders AS (
  SELECT
    ORDER_ID,
    LOCATION_ID,
    CUSTOMER_ID,
    SUBTOTAL_CENTS,
    TAX_PAID_CENTS,
    ORDER_TOTAL_CENTS,
    SUBTOTAL,
    TAX_PAID,
    ORDER_TOTAL,
    ORDERED_AT,
    ORDER_COST,
    ORDER_ITEMS_SUBTOTAL,
    COUNT_FOOD_ITEMS,
    COUNT_DRINK_ITEMS,
    COUNT_ORDER_ITEMS,
    IS_FOOD_ORDER,
    IS_DRINK_ORDER,
    CUSTOMER_ORDER_NUMBER
  FROM {{ ref('orders') }}
), projection_f13e AS (
  SELECT
    CUSTOMER_ID AS CUSTOMERS_CUSTOMER_ID,
    CUSTOMER_NAME
  FROM stg_customers
), formula_2164 AS (
  SELECT
    *,
    COUNT(DISTINCT ORDER_ID) > 1 AS IS_REPEAT_BUYER
  FROM orders
), aggregation_d1a7 AS (
  SELECT
    CUSTOMER_ID,
    COUNT(DISTINCT ORDER_ID) AS COUNT_LIFETIME_ORDERS,
    MIN(ORDERED_AT) AS FIRST_ORDERED_AT,
    MAX(ORDERED_AT) AS LAST_ORDERED_AT,
    SUM(SUBTOTAL) AS LIFETIME_SPEND_PRETAX,
    SUM(TAX_PAID) AS LIFETIME_TAX_PAID,
    SUM(ORDER_TOTAL) AS LIFETIME_SPEND
  FROM formula_2164
  GROUP BY
    CUSTOMER_ID
), projection_6683 AS (
  SELECT
    CUSTOMER_ID AS CUSTOMER_ORDERS_SUMMARY_CUSTOMER_ID,
    COUNT_LIFETIME_ORDERS,
    IS_REPEAT_BUYER,
    FIRST_ORDERED_AT,
    LAST_ORDERED_AT,
    LIFETIME_SPEND_PRETAX,
    LIFETIME_TAX_PAID,
    LIFETIME_SPEND
  FROM aggregation_d1a7
), join_889a AS (
  SELECT
    *
  FROM projection_f13e
  LEFT JOIN projection_6683
    ON projection_f13e.CUSTOMERS_CUSTOMER_ID = projection_6683.CUSTOMER_ORDERS_SUMMARY_CUSTOMER_ID
), formula_9f6a AS (
  SELECT
    *,
    CASE WHEN IS_REPEAT_BUYER THEN 'returning' ELSE 'new' END AS CUSTOMER_TYPE
  FROM join_889a
), projection_5612 AS (
  SELECT
    CUSTOMERS_CUSTOMER_ID AS CUSTOMER_ID,
    CUSTOMER_NAME,
    COUNT_LIFETIME_ORDERS,
    FIRST_ORDERED_AT,
    LAST_ORDERED_AT,
    LIFETIME_SPEND_PRETAX,
    LIFETIME_TAX_PAID,
    LIFETIME_SPEND,
    CUSTOMER_TYPE
  FROM formula_9f6a
), customers AS (
  SELECT
    *
  FROM projection_5612
)
SELECT
  *
FROM customers