WITH stg_orders AS (
  SELECT
    *
  FROM {{ ref('stg_orders') }}
), order_items AS (
  SELECT
    ORDER_ITEM_ID,
    ORDER_ID,
    PRODUCT_ID,
    ORDERED_AT,
    PRODUCT_NAME,
    PRODUCT_PRICE,
    IS_FOOD_ITEM,
    IS_DRINK_ITEM,
    SUPPLY_COST
  FROM {{ ref('order_items') }}
), rename_1 AS (
  SELECT
    ORDER_ID AS ORDERS_ORDER_ID,
    LOCATION_ID,
    CUSTOMER_ID,
    SUBTOTAL_CENTS,
    TAX_PAID_CENTS,
    ORDER_TOTAL_CENTS,
    SUBTOTAL,
    TAX_PAID,
    ORDER_TOTAL,
    ORDERED_AT
  FROM stg_orders
), formula_1 AS (
  SELECT
    *,
    CASE WHEN IS_FOOD_ITEM THEN 1 ELSE 0 END AS AGG_COUNT_FOOD_ITEMS_INPUT,
    CASE WHEN IS_DRINK_ITEM THEN 1 ELSE 0 END AS AGG_COUNT_DRINK_ITEMS_INPUT
  FROM order_items
), aggregate_1 AS (
  SELECT
    ORDER_ID,
    SUM(SUPPLY_COST) AS ORDER_COST,
    SUM(PRODUCT_PRICE) AS ORDER_ITEMS_SUBTOTAL,
    COUNT(ORDER_ITEM_ID) AS COUNT_ORDER_ITEMS,
    SUM(AGG_COUNT_FOOD_ITEMS_INPUT) AS COUNT_FOOD_ITEMS,
    SUM(AGG_COUNT_DRINK_ITEMS_INPUT) AS COUNT_DRINK_ITEMS
  FROM formula_1
  GROUP BY
    ORDER_ID
), rename_2 AS (
  SELECT
    ORDER_ID AS ORDER_ITEMS_SUMMARY_ORDER_ID,
    ORDER_COST,
    ORDER_ITEMS_SUBTOTAL,
    COUNT_ORDER_ITEMS,
    COUNT_FOOD_ITEMS,
    COUNT_DRINK_ITEMS
  FROM aggregate_1
), join_1 AS (
  SELECT
    *
  FROM rename_1
  LEFT JOIN rename_2
    ON rename_1.ORDERS_ORDER_ID = rename_2.ORDER_ITEMS_SUMMARY_ORDER_ID
), formula_2 AS (
  SELECT
    *,
    COUNT_FOOD_ITEMS > 0 AS IS_FOOD_ORDER,
    COUNT_DRINK_ITEMS > 0 AS IS_DRINK_ORDER
  FROM join_1
), rename_3 AS (
  SELECT
    ORDERS_ORDER_ID AS ORDER_ID,
    LOCATION_ID,
    CUSTOMER_ID,
    SUBTOTAL_CENTS,
    TAX_PAID_CENTS,
    ORDER_TOTAL_CENTS,
    SUBTOTAL,
    TAX_PAID,
    ORDER_TOTAL,
    ORDERED_AT,
    ORDER_COST,
    ORDER_ITEMS_SUBTOTAL,
    COUNT_FOOD_ITEMS,
    COUNT_DRINK_ITEMS,
    COUNT_ORDER_ITEMS,
    IS_FOOD_ORDER,
    IS_DRINK_ORDER
  FROM formula_2
), formula_3 AS (
  SELECT
    *,
    ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDERED_AT ASC) AS CUSTOMER_ORDER_NUMBER
  FROM rename_3
), orders AS (
  SELECT
    ORDER_ID,
    LOCATION_ID,
    CUSTOMER_ID,
    SUBTOTAL_CENTS,
    TAX_PAID_CENTS,
    ORDER_TOTAL_CENTS,
    SUBTOTAL,
    TAX_PAID,
    ORDER_TOTAL,
    ORDERED_AT,
    ORDER_COST,
    ORDER_ITEMS_SUBTOTAL,
    COUNT_FOOD_ITEMS,
    COUNT_DRINK_ITEMS,
    COUNT_ORDER_ITEMS,
    IS_FOOD_ORDER,
    IS_DRINK_ORDER,
    CUSTOMER_ORDER_NUMBER
  FROM formula_3
)
SELECT
  *
FROM orders